<?php 
//include the database connectivity setting
include ("inc/dbconn.php");?>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>New member registration</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <!-- Loading Flat UI Pro -->
    <link href="css/flat-ui-pro.css" rel="stylesheet">
    <link rel="shortcut icon" href="img/favicon.png">
  
</head>
<body>

<?php 
//include the navigation bar
include ("inc/navbar.php");?>

<div class="container">
	<br>
	<br>
  

  <div class="row">
    
    <div class="col-md-9" name="maincontent" id="maincontent">
		
		<div id="exercise" name="exercise" class="panel panel-info">
		<div class="panel-heading"><h5>Registration Form</h5></div>
			<div class="panel-body">
			<!-- ***********Edit your content STARTS from here******** -->
				New member info<br>
				<form role="form" name="" action="" method="GET">
					<div class="form-group">
					  Member ID <input class="form-control" name="empno" type="text" 
					  placeholder ="Autogenerated" readonly>
					  Firstname <input class="form-control" name="firstname" type="text" 
					  placeholder ="Firstname here..." required>
					  Lastname <input class="form-control" name="lastname" type="text" 
					  placeholder ="Lastname here..." >
					  Address <input class="form-control" name="address" type="text" 
					  placeholder ="Address here..." required>
					  Phone <input class="form-control" name="phoneno" type="text" maxlength="10" 
					  placeholder="10 digit phone number..." required>
					  
					  <input class="btn btn-embosed btn-primary" type="submit" value="Register new member" >
					</div>
				</form>
				<hr>
						
				<?php
				//check staff name input by the user if null
				if(!isset($_GET['firstname']) && !isset($_GET['address']) && !isset($_GET['phoneno'])){
					
				}
				else{//if there's user search - then perform db search
				//Create SQL query
					$firstname=$_GET['firstname'];
					$lastname=$_GET['lastname'];
					$address=$_GET['address'];
					$phoneno=$_GET['phoneno'];
					$query="INSERT INTO members(FName, LName, Address, Phone) 
					values ('$firstname','$lastname','$address','$phoneno')";
					//Execute the query
					$qr=mysqli_query($db,$query);
					if($qr==false){
						echo ("Query cannot be executed!<br>");
						echo ("SQL Error : ".mysqli_error($db));
					}
					else{//insert successfull
						echo "The new member has been registered with Member ID : ";
					    echo mysqli_insert_id($db);
						//echo  mysqli_insert_id($db);
						//echo "<a href='php-db-template.php?staffname=$firstname'>View $firstname $lastname</a>";
					}
				}
				?>
			
			<!-- ***********Edit your content ENDS here******** -->	
			</div> <!--body panel main -->
		</div><!--toc -->
		
    </div><!-- end main content -->
	
    <div class="col-md-3">
		<?php 
		//include the sidebar menu
		include ("inc/sidebar-menu.php");?>
    </div><!-- end main menu -->
  </div>
</div><!-- end container -->


<?php 
//include the footer
include ("inc/footer.php");?>

</body>
</html>
